### ISSUE TITLE
No Host Specified

### ISSUE THREAD

**Issue by daedric7** [smilebasti/npmGrafStats#29]
I don't think npmgraf likes my logs :/

```
stats-npmgraf-1  | Internal IP-Source: 130.61.129.53 called: thelounge.aguiarvieira.pt
stats-npmgraf-1  | Traceback (most recent call last):
stats-npmgraf-1  |   File "/root/.config/NPMGRAF/Getipinfo.py", line 122, in <module>
stats-npmgraf-1  | **************** start *********************
stats-npmgraf-1  | Measurement-name: ReverseProxyConnections
stats-npmgraf-1  | Portugal
stats-npmgraf-1  | Porto
stats-npmgraf-1  | Maia
stats-npmgraf-1  | 4470-070
stats-npmgraf-1  | -8.6182
stats-npmgraf-1  | 41.2345
stats-npmgraf-1  | PT
stats-npmgraf-1  | Outside IP:  2.82.30.18
stats-npmgraf-1  | Target IP:  2.82.30.18
stats-npmgraf-1  | Domain:  aguiarvieira.pt
stats-npmgraf-1  | Measurement Time:  2023-09-15T22:27:13+00:00
stats-npmgraf-1  |     write_api.write(bucket=ifbucket, org=iforg, record=point)
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/client/write_api.py", line 378, in write
stats-npmgraf-1  |     results = list(map(write_payload, payloads.items()))
stats-npmgraf-1  |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/client/write_api.py", line 376, in write_payload
stats-npmgraf-1  |     return self._post_write(_async_req, bucket, org, final_string, payload[0])
stats-npmgraf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/client/write_api.py", line 509, in _post_write
stats-npmgraf-1  |     return self._write_service.post_write(org=org, bucket=bucket, body=body, precision=precision,
stats-npmgraf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/service/write_service.py", line 60, in post_write
stats-npmgraf-1  |     (data) = self.post_write_with_http_info(org, bucket, body, **kwargs)  # noqa: E501
stats-npmgraf-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/service/write_service.py", line 90, in post_write_with_http_info
stats-npmgraf-1  |     return self.api_client.call_api(
stats-npmgraf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/api_client.py", line 343, in call_api
stats-npmgraf-1  |     return self.__call_api(resource_path, method,
stats-npmgraf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/api_client.py", line 173, in __call_api
stats-npmgraf-1  |     response_data = self.request(
stats-npmgraf-1  |                     ^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/api_client.py", line 388, in request
stats-npmgraf-1  |     return self.rest_client.POST(url,
stats-npmgraf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/rest.py", line 311, in POST
stats-npmgraf-1  |     return self.request("POST", url,
stats-npmgraf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/influxdb_client/_sync/rest.py", line 220, in request
stats-npmgraf-1  |     r = self.pool_manager.request(
stats-npmgraf-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/_request_methods.py", line 118, in request
stats-npmgraf-1  |     return self.request_encode_body(
stats-npmgraf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/_request_methods.py", line 217, in request_encode_body
stats-npmgraf-1  |     return self.urlopen(method, url, **extra_kw)
stats-npmgraf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 432, in urlopen
stats-npmgraf-1  |     conn = self.connection_from_host(u.host, port=u.port, scheme=u.scheme)
stats-npmgraf-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
stats-npmgraf-1  |   File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 294, in connection_from_host
stats-npmgraf-1  |     raise LocationValueError("No host specified.")
stats-npmgraf-1  | urllib3.exceptions.LocationValueError: No host specified.

```

Although i have some custom log formats, they are not on that log dir...

Example of a log:

```
[15/Sep/2023:22:30:14 +0000] - 200 200 - GET https aguiarvieira.pt "/_matrix/client/versions" [Client 2.82.30.18] [Length 867] [Gzip -] [Sent-to matrix-element] "mtxclient v0.9.2" "-"
[15/Sep/2023:22:30:21 +0000] - 200 200 - POST https aguiarvieira.pt "/_matrix/client/v3/publicRooms" [Client 130.61.129.53] [Length 2916] [Gzip -] [Sent-to matrix-element] "undici" "-"
[15/Sep/2023:22:30:23 +0000] - 200 200 - GET https aguiarvieira.pt "/_synapse/admin/v1/event_reports?dir=f&from=0&dir=f&from=0" [Client 130.61.129.53] [Length 650] [Gzip -] [Sent-to matrix-element] "Python/3.8 aiohttp/3.8.5" "-"
[15/Sep/2023:22:30:29 +0000] - 200 200 - GET https aguiarvieira.pt "/_matrix/client/versions" [Client 2.82.30.18] [Length 867] [Gzip -] [Sent-to matrix-element] "mtxclient v0.9.2" "-"
[15/Sep/2023:22:30:44 +0000] - 200 200 - GET https aguiarvieira.pt "/_matrix/client/versions" [Client 2.82.30.18] [Length 867] [Gzip -] [Sent-to matrix-element] "mtxclient v0.9.2" "-"
[15/Sep/2023:22:30:53 +0000] - 200 200 - GET https aguiarvieira.pt "/_synapse/admin/v1/event_reports?dir=f&from=0&dir=f&from=0" [Client 130.61.129.53] [Length 650] [Gzip -] [Sent-to matrix-element] "Python/3.8 aiohttp/3.8.5" "-"
[15/Sep/2023:22:30:59 +0000] - 304 304 - GET https aguiarvieira.pt "/version" [Client 2.82.30.18] [Length 0] [Gzip -] [Sent-to matrix-element] "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36" "-"
```

**Comment by smilebasti** [comment]
Hi,
this is not a logs problem. 
`No host specified`, `Traceback (most recent call last): File "/root/.config/NPMGRAF/Getipinfo.py", line 122, in <module>` and the fact that the logs show the Measurement Time (last think before sending them to influx), this seems that the container isn't able to talk to your influxdbv2. Or you haven't set one `No host specified`.

Please test your InfluxDBv2 connection.

**Comment by daedric7** [comment]
npmgraf, influxdb2 and npm are on the same network.

I can reach the webui from npm, so the hostname should be ok. 

Also, from npmgraf container i can reach influxdb:

```
docker compose exec npmgraf sh
# curl influxdb
curl: (7) Failed to connect to influxdb port 80 after 1 ms: Couldn't connect to server
# curl influxdb:8086
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="InfluxDB is a time series platform, purpose-built by InfluxData for storing metrics and events, provides real-time visibility into stacks, sensors, and systems."><title>InfluxDB</title><base href="/"><base href=""><link rel="icon" href="/favicon.ico"></head><body><div id="react-root" data-basepath=""></div><script defer="defer" src="/fa4773d142.js"></script></body></html>
```

**Comment by smilebasti** [comment]
Ok. Are you using the container name in a docker network?

Can you please test it again with an IP address. Either the Host or VM IP or maybe the docker network IP if it's all running in a docker network.

**Comment by daedric7** [comment]
Apologies for the lack of replys :)

`INFLUX_HOST: 'localip:8086' # use host IP`

I think i have progress :) 

```
stats-npmgraf-1  | **************** start *********************
stats-npmgraf-1  | Measurement-name: ReverseProxyConnections
stats-npmgraf-1  | Hungary
stats-npmgraf-1  | Budapest
stats-npmgraf-1  | Budapest
stats-npmgraf-1  | 1125
stats-npmgraf-1  | 19.0947
stats-npmgraf-1  | 47.5636
stats-npmgraf-1  | HU
stats-npmgraf-1  | Outside IP:  46.139.3.54
stats-npmgraf-1  | Target IP:  46.139.3.54
stats-npmgraf-1  | Domain:  aguiarvieira.pt
stats-npmgraf-1  | Measurement Time:  2023-09-17T15:33:52+00:00
stats-npmgraf-1  | *************** data send ******************
```

**Comment by smilebasti** [comment]
That seem`s to work. What was the issue?

One thing is of. The Target IP should be in your network and not the same as Outside. So you have changed the logging sheme for that?

**Comment by daedric7** [comment]
It seems npmgraft does not like to resolve hostname ->IP when connecting to Influx...

Regarding your question, i don't think i've changed anything, but that specific host is a Matrix host, it's quite complex with many forwards on the advanced that, lots of options, and also specific loggings per location.

**Comment by smilebasti** [comment]
Ah ok. This seems to be a problem with the python package `influxdb-client`.

Ok. Then i will close this issue. Enjoy.
