### ISSUE TITLE
no data displayed in grafana

### ISSUE THREAD

**Issue by sistemmsn** [smilebasti/npmGrafStats#47]
I don't understand why it doesn't give me data in Grafana
![image](https://github.com/user-attachments/assets/f6558bea-23b6-47e9-83c4-dcb2e40ca5a9)

![image](https://github.com/user-attachments/assets/6a894beb-9977-421f-9d8b-507630704ea7)

`Internal IP-Source: 172.17.0.1 called: meta.levecs.com
Internal IP-Source: 172.17.0.1 called: meta.levecs.com
**************** start *********************
Measurement-name: ReverseProxyConnections
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
    response = reader.asn(str(sys.argv[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.
**************** start *********************
Measurement-name: ReverseProxyConnections
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
    response = reader.asn(str(sys.argv[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
**************** start *********************
Measurement-name: ReverseProxyConnections
    response = reader.asn(str(sys.argv[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
    response = reader.asn(str(sys.argv[1]))
**************** start *********************
Measurement-name: ReverseProxyConnections
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
**************** start *********************
Measurement-name: ReverseProxyConnections
    response = reader.asn(str(sys.argv[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.
**************** start *********************
Measurement-name: ReverseProxyConnections
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
    response = reader.asn(str(sys.argv[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.
**************** start *********************
Measurement-name: ReverseProxyConnections
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
    response = reader.asn(str(sys.argv[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.
**************** start *********************
Measurement-name: ReverseProxyConnections
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
    response = reader.asn(str(sys.argv[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
**************** start *********************
Measurement-name: ReverseProxyConnections
    response = reader.asn(str(sys.argv[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.
**************** start *********************
Measurement-name: ReverseProxyConnections
Traceback (most recent call last):
  File "/root/.config/NPMGRAF/Getipinfo.py", line 59, in <module>
    response = reader.asn(str(sys.argv[1]))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 176, in asn
    ASN, self._flat_model_for(geoip2.models.ASN, "GeoLite2-ASN", ip_address)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 267, in _flat_model_for
    (record, prefix_len) = self._get(types, ip_address)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/geoip2/database.py", line 240, in _get
    raise geoip2.errors.AddressNotFoundError(
geoip2.errors.AddressNotFoundError: The address 1.2.8.1 is not in the database.`

**Comment by smilebasti** [comment]
Hi, can you please share your environments variables you set.

**Comment by sistemmsn** [comment]
@smilebasti of course

`version: '3'
services:
  npmgraf:
    image: smilebasti/npmgrafstats:latest 
    restart: unless-stopped
    hostname: npmgraf
    environment:
      REDIRECTION_LOGS: TRUE
      INTERNAL_LOGS: TRUE
      MONITORING_LOGS: TRUE
      INFLUX_HOST: influxdb_nginx:8086
      INFLUX_BUCKET: npmgrafstats
      INFLUX_ORG: npmgrafstats
      INFLUX_TOKEN: 232123132123123123132132
    volumes:
      - /home/docker/nginx/data/logs:/logs
      - /home/docker/nginx/geolite:/geolite
      - /home/docker/nginx/monitoringips.txt:/monitoringips.txt
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - geoipupdate
    networks:
      - proxy

  influxdb_nginx:
    image: influxdb:2.7-alpine
    hostname: influxdb_nginx
    restart: unless-stopped
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: npmgrafstats
      DOCKER_INFLUXDB_INIT_PASSWORD: 121313313
      DOCKER_INFLUXDB_INIT_ORG: npmgrafstats
      DOCKER_INFLUXDB_INIT_BUCKET: npmgrafstats
    volumes:
      - /home/docker/nginx/influxdbv2:/var/lib/influxdb2
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

  geoipupdate:
    image: maxmindinc/geoipupdate
    hostname: geoipupdate
    restart: unless-stopped
    environment:
      GEOIPUPDATE_ACCOUNT_ID: 1213131
      GEOIPUPDATE_LICENSE_KEY: 123365656
      GEOIPUPDATE_EDITION_IDS: GeoLite2-ASN GeoLite2-City GeoLite2-Country
      GEOIPUPDATE_FREQUENCY: 24
    volumes:
      - /home/docker/nginx/geolite:/usr/share/GeoIP
      - /etc/localtime:/etc/localtime:ro
    networks:
      - proxy

networks:
  proxy:
    external: true
`

**Comment by JuliusSupergenius** [comment]
Try changing:

INFLUX_HOST: influxdb_nginx:8086

To:

INFLUX_HOST: 'http://influxdb_nginx:8086'

**Comment by JuliusBlueTek** [comment]
Try changing:

INFLUX_HOST: influxdb_nginx:8086

To:

INFLUX_HOST: 'http://influxdb_nginx:8086'

**Comment by KoenM9264** [comment]
i have the exact same issue

**Comment by KoenM9264** [comment]
My INFLUX_HOST is set to the following in my docker-compose.yml:

INFLUX_HOST: 'http://host.docker.internal:8086'

i do not have influxdb_nginx as an option.

i can send the docker compose file as well.

**Comment by JuliusSupergenius** [comment]
> My INFLUX_HOST is set to the following in my docker-compose.yml:
> 
> INFLUX_HOST: 'http://host.docker.internal:8086'
> 
> i do not have influxdb_nginx as an option.
> 
> i can send the docker compose file as well.

Are you using a different influxbd outside of the  compose? If you are and it’s hosted in the same docker instance then you can set the hostname to whatever but the hostname is just for cross docker connections and shouldn’t have dots.  If it’s on a different server then you should be able to use a dns lookup able address like you have.

Basically add a hostname to your DB like:

image: influxdb:2.7-alpine
hostname: influxgraphdb

Then set that hostname as the address

INFLUX_HOST: 'http://influxgraphdb:8086'

**Comment by KoenM9264** [comment]
ah, ok. So i should not be using an ip address or host.docker.internal if on the same machine? I should instead be using the containers name/hostname correct?

Thanks!

**Comment by sistemmsn** [comment]
Hello, it still does not work.

**Comment by smilebasti** [comment]
Please test it with the new release v2.4.3. If it doesn't work please let me know.

And sorry for the late fix
